---
title: "KidGoal_Clean_Pixel_Files"
author: "Jessica Kosie"
date: "April 13, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse); library(here); library(assertthat)

source("helper/file_read_helper.R")

```
# Read in txt files
```{r read in txt files}
data_path <- "data/pixel_data/"
file_list <- dir(data_path)

pix_data <- map_df(file_list, clean_pixel_file)

#remove last slide
pix_data <- pix_data %>% 
  filter(slide_num_adj != 20)

```
# Take a look at the data across conditions
```{r}
#plot on separate graphs
pix_data %>% 
  ggplot(aes(x = slide_num_adj, y = pix_change, color = condition)) +
    geom_line() +
    geom_vline(xintercept = c(2, 9, 17), linetype = "dashed") +
    facet_wrap(~condition, ncol = 1) 

#plot on the same graph
pix_data %>% 
  ggplot(aes(x = slide_num_adj, y = pix_change, color = condition)) +
    geom_line() +
    geom_vline(xintercept = c(2, 9, 17), linetype = "dashed")

```
# Adjust for total number of pixels in image
```{r}
pix_data <- pix_data %>% 
  mutate(pix_adj = pix_change/(599*960))

#plot on separate graphs
pix_data %>% 
  ggplot(aes(x = slide_num_adj, y = pix_adj, color = condition)) +
    geom_line() +
    geom_vline(xintercept = c(2, 9, 17), linetype = "dashed") +
    facet_wrap(~condition, ncol = 1) 

#plot on the same graph
pix_data %>% 
  ggplot(aes(x = slide_num_adj, y = pix_adj, color = condition)) +
    geom_line() +
    geom_vline(xintercept = c(2, 9, 17), linetype = "dashed")

```
# Write to a csv file
```{r pixel data csv}
write_csv(pix_data, 'data/pixel_change_data.csv')



```
